/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'mood' : IDL.Text,
  'timestamp' : Time,
});
export const Reflection = IDL.Record({
  'id' : IDL.Text,
  'response' : IDL.Text,
  'timestamp' : Time,
  'prompt' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
export const CompanionDump = IDL.Record({
  'id' : IDL.Text,
  'releasedPermanently' : IDL.Bool,
  'voiceDurationSeconds' : IDL.Opt(IDL.Nat),
  'contentType' : IDL.Text,
  'source' : IDL.Text,
  'exhaleMessageShown' : IDL.Text,
  'createdAt' : Time,
  'crisisResourcesShown' : IDL.Bool,
  'crisisSignalDetected' : IDL.Bool,
  'streakDay' : IDL.Nat,
  'visibility' : IDL.Text,
  'audioStored' : IDL.Bool,
  'textContent' : IDL.Opt(IDL.Text),
});
export const Stats = IDL.Record({
  'totalEntries' : IDL.Nat,
  'moodFrequency' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'addReflection' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteJournalEntry' : IDL.Func([IDL.Text], [], []),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getAllReflections' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanionDumps' : IDL.Func([], [IDL.Vec(CompanionDump)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTodaysDump' : IDL.Func([], [IDL.Opt(CompanionDump)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCompanionDump' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
  'updateProfile' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'mood' : IDL.Text,
    'timestamp' : Time,
  });
  const Reflection = IDL.Record({
    'id' : IDL.Text,
    'response' : IDL.Text,
    'timestamp' : Time,
    'prompt' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
  const CompanionDump = IDL.Record({
    'id' : IDL.Text,
    'releasedPermanently' : IDL.Bool,
    'voiceDurationSeconds' : IDL.Opt(IDL.Nat),
    'contentType' : IDL.Text,
    'source' : IDL.Text,
    'exhaleMessageShown' : IDL.Text,
    'createdAt' : Time,
    'crisisResourcesShown' : IDL.Bool,
    'crisisSignalDetected' : IDL.Bool,
    'streakDay' : IDL.Nat,
    'visibility' : IDL.Text,
    'audioStored' : IDL.Bool,
    'textContent' : IDL.Opt(IDL.Text),
  });
  const Stats = IDL.Record({
    'totalEntries' : IDL.Nat,
    'moodFrequency' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addReflection' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteJournalEntry' : IDL.Func([IDL.Text], [], []),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getAllReflections' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanionDumps' : IDL.Func([], [IDL.Vec(CompanionDump)], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTodaysDump' : IDL.Func([], [IDL.Opt(CompanionDump)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCompanionDump' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'updateProfile' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };