/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'mood' : IDL.Text,
  'timestamp' : Time,
});
export const Reflection = IDL.Record({
  'id' : IDL.Text,
  'response' : IDL.Text,
  'timestamp' : Time,
  'prompt' : IDL.Text,
});
export const ApologyEntry = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'editLevel' : IDL.Text,
  'nonVeilToken' : IDL.Opt(IDL.Text),
  'signature' : IDL.Text,
  'emotionType' : IDL.Text,
  'sharedSilenceTriggered' : IDL.Bool,
  'content' : IDL.Text,
  'deliveredAt' : IDL.Opt(IDL.Int),
  'acknowledgedAt' : IDL.Opt(IDL.Int),
  'aiVersionUsed' : IDL.Text,
  'source' : IDL.Text,
  'createdAt' : IDL.Int,
  'recipientContact' : IDL.Opt(IDL.Text),
  'aiAssisted' : IDL.Bool,
  'isAnonymous' : IDL.Bool,
  'deliveryMethod' : IDL.Text,
  'deliveryTime' : IDL.Opt(IDL.Int),
  'recipientUserId' : IDL.Opt(IDL.Principal),
  'rescheduleCount' : IDL.Nat,
  'crisisSignalDetected' : IDL.Bool,
  'visibility' : IDL.Text,
  'recipientType' : IDL.Text,
  'senderUserId' : IDL.Principal,
  'nonVeilTokenExpires' : IDL.Opt(IDL.Int),
  'openedAt' : IDL.Opt(IDL.Int),
});
export const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
export const CompanionDump = IDL.Record({
  'id' : IDL.Text,
  'releasedPermanently' : IDL.Bool,
  'voiceDurationSeconds' : IDL.Opt(IDL.Nat),
  'contentType' : IDL.Text,
  'source' : IDL.Text,
  'exhaleMessageShown' : IDL.Text,
  'createdAt' : Time,
  'crisisResourcesShown' : IDL.Bool,
  'crisisSignalDetected' : IDL.Bool,
  'streakDay' : IDL.Nat,
  'visibility' : IDL.Text,
  'audioStored' : IDL.Bool,
  'textContent' : IDL.Opt(IDL.Text),
});
export const EmotionEntry = IDL.Record({
  'id' : IDL.Text,
  'emotionType' : IDL.Text,
  'aiPromptText' : IDL.Opt(IDL.Text),
  'customEmotionLabel' : IDL.Opt(IDL.Text),
  'voiceDurationSeconds' : IDL.Opt(IDL.Nat),
  'source' : IDL.Text,
  'emotionLabel' : IDL.Text,
  'exhaleMessageShown' : IDL.Text,
  'createdAt' : Time,
  'emoji' : IDL.Text,
  'crisisResourcesShown' : IDL.Bool,
  'crisisSignalDetected' : IDL.Bool,
  'visibilityLevel' : IDL.Text,
  'aiPromptShown' : IDL.Bool,
  'textReflection' : IDL.Opt(IDL.Text),
  'voiceOverrideApplied' : IDL.Bool,
});
export const EmotionStreakRecord = IDL.Record({
  'acknowledgmentType' : IDL.Opt(IDL.Text),
  'emotionType' : IDL.Text,
  'lastAwarenessShownAt' : IDL.Opt(IDL.Int),
  'updatedAt' : IDL.Int,
  'crisisResourcesShown' : IDL.Bool,
  'lastAwarenessMilestone' : IDL.Opt(IDL.Nat),
});
export const ApologySchedule = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'deliveredAt' : IDL.Opt(IDL.Int),
  'apologyId' : IDL.Text,
  'rescheduleCount' : IDL.Nat,
  'cancelledAt' : IDL.Opt(IDL.Int),
  'scheduledDeliveryTime' : IDL.Int,
  'reminderSent' : IDL.Bool,
  'reminderSentAt' : IDL.Opt(IDL.Int),
  'senderUserId' : IDL.Principal,
});
export const ApologyReceiverReflection = IDL.Record({
  'id' : IDL.Text,
  'completedAt' : IDL.Opt(IDL.Int),
  'emotionSelected' : IDL.Text,
  'receiverUserId' : IDL.Principal,
  'journalEntryId' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'privateReflectionText' : IDL.Opt(IDL.Text),
  'apologyId' : IDL.Text,
  'actionTaken' : IDL.Text,
  'reflectionComplete' : IDL.Bool,
});
export const Stats = IDL.Record({
  'totalEntries' : IDL.Nat,
  'moodFrequency' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'currentStreak' : IDL.Nat,
});
export const VeilVoiceMomentsEnabled = IDL.Record({
  'after_checkin' : IDL.Bool,
  'carrying_awareness' : IDL.Bool,
  'after_silent_dump' : IDL.Bool,
  'after_text_dump' : IDL.Bool,
  'after_voice_dump' : IDL.Bool,
  'morning_follow_up' : IDL.Bool,
});
export const VeilVoiceSettings = IDL.Record({
  'moments_enabled' : VeilVoiceMomentsEnabled,
  'onboarding_completed' : IDL.Bool,
  'voice_enabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeApologyOpened' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'addReflection' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelApologySchedule' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createApology' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Text],
      [],
    ),
  'deleteAllMyApologies' : IDL.Func([], [IDL.Bool], []),
  'deleteJournalEntry' : IDL.Func([IDL.Text], [], []),
  'deleteUnsentApology' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllApologySenderIds' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getAllReflections' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
  'getApologyById' : IDL.Func([IDL.Text], [IDL.Opt(ApologyEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanionDumps' : IDL.Func([], [IDL.Vec(CompanionDump)], ['query']),
  'getEmotionEntries' : IDL.Func([], [IDL.Vec(EmotionEntry)], ['query']),
  'getEmotionStreakRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(EmotionStreakRecord)],
      ['query'],
    ),
  'getInnerCircle' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMyApologies' : IDL.Func([], [IDL.Vec(ApologyEntry)], ['query']),
  'getMyScheduledApologies' : IDL.Func(
      [],
      [IDL.Vec(ApologySchedule)],
      ['query'],
    ),
  'getMyUnsentApologies' : IDL.Func([], [IDL.Vec(ApologyEntry)], ['query']),
  'getReceivedApologies' : IDL.Func([], [IDL.Vec(ApologyEntry)], ['query']),
  'getReceiverReflection' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ApologyReceiverReflection)],
      ['query'],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTodaysDump' : IDL.Func([], [IDL.Opt(CompanionDump)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVeilVoiceSettings' : IDL.Func(
      [],
      [IDL.Opt(VeilVoiceSettings)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rescheduleApology' : IDL.Func([IDL.Text, IDL.Int], [IDL.Bool], []),
  'saveApologyAsUnsent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCompanionDump' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Nat,
      ],
      [IDL.Text],
      [],
    ),
  'saveEmotionEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'saveEmotionStreakRecord' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text), IDL.Bool],
      [],
      [],
    ),
  'saveReceiverReflection' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Bool],
      [],
    ),
  'saveVeilVoiceSettings' : IDL.Func(
      [
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'scheduleApology' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Principal), IDL.Text, IDL.Opt(IDL.Text), IDL.Int],
      [IDL.Bool],
      [],
    ),
  'sendApologyNow' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Principal), IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateApologyContent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'mood' : IDL.Text,
    'timestamp' : Time,
  });
  const Reflection = IDL.Record({
    'id' : IDL.Text,
    'response' : IDL.Text,
    'timestamp' : Time,
    'prompt' : IDL.Text,
  });
  const ApologyEntry = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'editLevel' : IDL.Text,
    'nonVeilToken' : IDL.Opt(IDL.Text),
    'signature' : IDL.Text,
    'emotionType' : IDL.Text,
    'sharedSilenceTriggered' : IDL.Bool,
    'content' : IDL.Text,
    'deliveredAt' : IDL.Opt(IDL.Int),
    'acknowledgedAt' : IDL.Opt(IDL.Int),
    'aiVersionUsed' : IDL.Text,
    'source' : IDL.Text,
    'createdAt' : IDL.Int,
    'recipientContact' : IDL.Opt(IDL.Text),
    'aiAssisted' : IDL.Bool,
    'isAnonymous' : IDL.Bool,
    'deliveryMethod' : IDL.Text,
    'deliveryTime' : IDL.Opt(IDL.Int),
    'recipientUserId' : IDL.Opt(IDL.Principal),
    'rescheduleCount' : IDL.Nat,
    'crisisSignalDetected' : IDL.Bool,
    'visibility' : IDL.Text,
    'recipientType' : IDL.Text,
    'senderUserId' : IDL.Principal,
    'nonVeilTokenExpires' : IDL.Opt(IDL.Int),
    'openedAt' : IDL.Opt(IDL.Int),
  });
  const UserProfile = IDL.Record({ 'displayName' : IDL.Text });
  const CompanionDump = IDL.Record({
    'id' : IDL.Text,
    'releasedPermanently' : IDL.Bool,
    'voiceDurationSeconds' : IDL.Opt(IDL.Nat),
    'contentType' : IDL.Text,
    'source' : IDL.Text,
    'exhaleMessageShown' : IDL.Text,
    'createdAt' : Time,
    'crisisResourcesShown' : IDL.Bool,
    'crisisSignalDetected' : IDL.Bool,
    'streakDay' : IDL.Nat,
    'visibility' : IDL.Text,
    'audioStored' : IDL.Bool,
    'textContent' : IDL.Opt(IDL.Text),
  });
  const EmotionEntry = IDL.Record({
    'id' : IDL.Text,
    'emotionType' : IDL.Text,
    'aiPromptText' : IDL.Opt(IDL.Text),
    'customEmotionLabel' : IDL.Opt(IDL.Text),
    'voiceDurationSeconds' : IDL.Opt(IDL.Nat),
    'source' : IDL.Text,
    'emotionLabel' : IDL.Text,
    'exhaleMessageShown' : IDL.Text,
    'createdAt' : Time,
    'emoji' : IDL.Text,
    'crisisResourcesShown' : IDL.Bool,
    'crisisSignalDetected' : IDL.Bool,
    'visibilityLevel' : IDL.Text,
    'aiPromptShown' : IDL.Bool,
    'textReflection' : IDL.Opt(IDL.Text),
    'voiceOverrideApplied' : IDL.Bool,
  });
  const EmotionStreakRecord = IDL.Record({
    'acknowledgmentType' : IDL.Opt(IDL.Text),
    'emotionType' : IDL.Text,
    'lastAwarenessShownAt' : IDL.Opt(IDL.Int),
    'updatedAt' : IDL.Int,
    'crisisResourcesShown' : IDL.Bool,
    'lastAwarenessMilestone' : IDL.Opt(IDL.Nat),
  });
  const ApologySchedule = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'deliveredAt' : IDL.Opt(IDL.Int),
    'apologyId' : IDL.Text,
    'rescheduleCount' : IDL.Nat,
    'cancelledAt' : IDL.Opt(IDL.Int),
    'scheduledDeliveryTime' : IDL.Int,
    'reminderSent' : IDL.Bool,
    'reminderSentAt' : IDL.Opt(IDL.Int),
    'senderUserId' : IDL.Principal,
  });
  const ApologyReceiverReflection = IDL.Record({
    'id' : IDL.Text,
    'completedAt' : IDL.Opt(IDL.Int),
    'emotionSelected' : IDL.Text,
    'receiverUserId' : IDL.Principal,
    'journalEntryId' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'privateReflectionText' : IDL.Opt(IDL.Text),
    'apologyId' : IDL.Text,
    'actionTaken' : IDL.Text,
    'reflectionComplete' : IDL.Bool,
  });
  const Stats = IDL.Record({
    'totalEntries' : IDL.Nat,
    'moodFrequency' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'currentStreak' : IDL.Nat,
  });
  const VeilVoiceMomentsEnabled = IDL.Record({
    'after_checkin' : IDL.Bool,
    'carrying_awareness' : IDL.Bool,
    'after_silent_dump' : IDL.Bool,
    'after_text_dump' : IDL.Bool,
    'after_voice_dump' : IDL.Bool,
    'morning_follow_up' : IDL.Bool,
  });
  const VeilVoiceSettings = IDL.Record({
    'moments_enabled' : VeilVoiceMomentsEnabled,
    'onboarding_completed' : IDL.Bool,
    'voice_enabled' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeApologyOpened' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'addJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addReflection' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelApologySchedule' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createApology' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Text],
        [],
      ),
    'deleteAllMyApologies' : IDL.Func([], [IDL.Bool], []),
    'deleteJournalEntry' : IDL.Func([IDL.Text], [], []),
    'deleteUnsentApology' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllApologySenderIds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getAllReflections' : IDL.Func([], [IDL.Vec(Reflection)], ['query']),
    'getApologyById' : IDL.Func([IDL.Text], [IDL.Opt(ApologyEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanionDumps' : IDL.Func([], [IDL.Vec(CompanionDump)], ['query']),
    'getEmotionEntries' : IDL.Func([], [IDL.Vec(EmotionEntry)], ['query']),
    'getEmotionStreakRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(EmotionStreakRecord)],
        ['query'],
      ),
    'getInnerCircle' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMyApologies' : IDL.Func([], [IDL.Vec(ApologyEntry)], ['query']),
    'getMyScheduledApologies' : IDL.Func(
        [],
        [IDL.Vec(ApologySchedule)],
        ['query'],
      ),
    'getMyUnsentApologies' : IDL.Func([], [IDL.Vec(ApologyEntry)], ['query']),
    'getReceivedApologies' : IDL.Func([], [IDL.Vec(ApologyEntry)], ['query']),
    'getReceiverReflection' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ApologyReceiverReflection)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTodaysDump' : IDL.Func([], [IDL.Opt(CompanionDump)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVeilVoiceSettings' : IDL.Func(
        [],
        [IDL.Opt(VeilVoiceSettings)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rescheduleApology' : IDL.Func([IDL.Text, IDL.Int], [IDL.Bool], []),
    'saveApologyAsUnsent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCompanionDump' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Nat,
        ],
        [IDL.Text],
        [],
      ),
    'saveEmotionEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'saveEmotionStreakRecord' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text), IDL.Bool],
        [],
        [],
      ),
    'saveReceiverReflection' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveVeilVoiceSettings' : IDL.Func(
        [
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'scheduleApology' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Principal),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Int,
        ],
        [IDL.Bool],
        [],
      ),
    'sendApologyNow' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Principal), IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateApologyContent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };