/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanionDump {
  'id' : string,
  'releasedPermanently' : boolean,
  'voiceDurationSeconds' : [] | [bigint],
  'contentType' : string,
  'source' : string,
  'exhaleMessageShown' : string,
  'createdAt' : Time,
  'crisisResourcesShown' : boolean,
  'crisisSignalDetected' : boolean,
  'streakDay' : bigint,
  'visibility' : string,
  'audioStored' : boolean,
  'textContent' : [] | [string],
}
export interface JournalEntry {
  'id' : string,
  'title' : string,
  'body' : string,
  'mood' : string,
  'timestamp' : Time,
}
export interface Reflection {
  'id' : string,
  'response' : string,
  'timestamp' : Time,
  'prompt' : string,
}
export interface Stats {
  'totalEntries' : bigint,
  'moodFrequency' : Array<[string, bigint]>,
  'currentStreak' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'displayName' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addJournalEntry' : ActorMethod<[string, string, string], string>,
  'addReflection' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteJournalEntry' : ActorMethod<[string], undefined>,
  'getAllJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getAllReflections' : ActorMethod<[], Array<Reflection>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanionDumps' : ActorMethod<[], Array<CompanionDump>>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getStats' : ActorMethod<[], Stats>,
  'getTodaysDump' : ActorMethod<[], [] | [CompanionDump]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCompanionDump' : ActorMethod<
    [string, [] | [string], [] | [bigint], boolean, boolean, string, bigint],
    string
  >,
  'updateProfile' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];