/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface Stats {
    totalEntries: bigint;
    moodFrequency: Array<[string, bigint]>;
    currentStreak: bigint;
}
export interface Reflection {
    id: string;
    response: string;
    timestamp: Time;
    prompt: string;
}
export interface ApologyReceiverReflection {
    id: string;
    completedAt?: bigint;
    emotionSelected: string;
    receiverUserId: Principal;
    journalEntryId?: string;
    createdAt: bigint;
    privateReflectionText?: string;
    apologyId: string;
    actionTaken: string;
    reflectionComplete: boolean;
}
export interface VeilVoiceSettings {
    moments_enabled: VeilVoiceMomentsEnabled;
    onboarding_completed: boolean;
    voice_enabled: boolean;
}
export interface VeilVoiceMomentsEnabled {
    after_checkin: boolean;
    carrying_awareness: boolean;
    after_silent_dump: boolean;
    after_text_dump: boolean;
    after_voice_dump: boolean;
    morning_follow_up: boolean;
}
export interface JournalEntry {
    id: string;
    title: string;
    body: string;
    mood: string;
    timestamp: Time;
}
export interface ApologyEntry {
    id: string;
    status: string;
    editLevel: string;
    nonVeilToken?: string;
    signature: string;
    emotionType: string;
    sharedSilenceTriggered: boolean;
    content: string;
    deliveredAt?: bigint;
    acknowledgedAt?: bigint;
    aiVersionUsed: string;
    source: string;
    createdAt: bigint;
    recipientContact?: string;
    aiAssisted: boolean;
    isAnonymous: boolean;
    deliveryMethod: string;
    deliveryTime?: bigint;
    recipientUserId?: Principal;
    rescheduleCount: bigint;
    crisisSignalDetected: boolean;
    visibility: string;
    recipientType: string;
    senderUserId: Principal;
    nonVeilTokenExpires?: bigint;
    openedAt?: bigint;
}
export interface EmotionEntry {
    id: string;
    emotionType: string;
    aiPromptText?: string;
    customEmotionLabel?: string;
    voiceDurationSeconds?: bigint;
    source: string;
    emotionLabel: string;
    exhaleMessageShown: string;
    createdAt: Time;
    emoji: string;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    visibilityLevel: string;
    aiPromptShown: boolean;
    textReflection?: string;
    voiceOverrideApplied: boolean;
}
export interface CompanionDump {
    id: string;
    releasedPermanently: boolean;
    voiceDurationSeconds?: bigint;
    contentType: string;
    source: string;
    exhaleMessageShown: string;
    createdAt: Time;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    streakDay: bigint;
    visibility: string;
    audioStored: boolean;
    textContent?: string;
}
export interface EmotionStreakRecord {
    acknowledgmentType?: string;
    emotionType: string;
    lastAwarenessShownAt?: bigint;
    updatedAt: bigint;
    crisisResourcesShown: boolean;
    lastAwarenessMilestone?: bigint;
}
export interface UserProfile {
    displayName: string;
}
export interface ApologySchedule {
    id: string;
    status: string;
    deliveredAt?: bigint;
    apologyId: string;
    rescheduleCount: bigint;
    cancelledAt?: bigint;
    scheduledDeliveryTime: bigint;
    reminderSent: boolean;
    reminderSentAt?: bigint;
    senderUserId: Principal;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acknowledgeApologyOpened(apologyId: string): Promise<boolean>;
    addJournalEntry(title: string, body: string, mood: string): Promise<string>;
    addReflection(prompt: string, response: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelApologySchedule(apologyId: string): Promise<boolean>;
    createApology(content: string, signature: string, emotionType: string, isAnonymous: boolean, aiAssisted: boolean, aiVersionUsed: string, source: string, crisisSignalDetected: boolean): Promise<string>;
    deleteAllMyApologies(): Promise<boolean>;
    deleteJournalEntry(id: string): Promise<void>;
    deleteUnsentApology(apologyId: string): Promise<boolean>;
    getAllApologySenderIds(): Promise<Array<Principal>>;
    getAllJournalEntries(): Promise<Array<JournalEntry>>;
    getAllReflections(): Promise<Array<Reflection>>;
    getApologyById(apologyId: string): Promise<ApologyEntry | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanionDumps(): Promise<Array<CompanionDump>>;
    getEmotionEntries(): Promise<Array<EmotionEntry>>;
    getEmotionStreakRecord(emotionType: string): Promise<EmotionStreakRecord | null>;
    getInnerCircle(): Promise<Array<Principal>>;
    getMyApologies(): Promise<Array<ApologyEntry>>;
    getMyScheduledApologies(): Promise<Array<ApologySchedule>>;
    getMyUnsentApologies(): Promise<Array<ApologyEntry>>;
    getReceivedApologies(): Promise<Array<ApologyEntry>>;
    getReceiverReflection(apologyId: string): Promise<ApologyReceiverReflection | null>;
    getStats(): Promise<Stats>;
    getTodaysDump(): Promise<CompanionDump | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVeilVoiceSettings(): Promise<VeilVoiceSettings | null>;
    isCallerAdmin(): Promise<boolean>;
    rescheduleApology(apologyId: string, newDeliveryTime: bigint): Promise<boolean>;
    saveApologyAsUnsent(apologyId: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCompanionDump(contentType: string, textContent: string | null, voiceDurationSeconds: bigint | null, crisisSignalDetected: boolean, crisisResourcesShown: boolean, exhaleMessageShown: string, streakDay: bigint): Promise<string>;
    saveEmotionEntry(emotionType: string, emotionLabel: string, emoji: string, customEmotionLabel: string | null, textReflection: string | null, voiceDurationSeconds: bigint | null, visibilityLevel: string, voiceOverrideApplied: boolean, aiPromptShown: boolean, aiPromptText: string | null, crisisSignalDetected: boolean, crisisResourcesShown: boolean, exhaleMessageShown: string): Promise<string>;
    saveEmotionStreakRecord(emotionType: string, lastAwarenessMilestone: bigint | null, acknowledgmentType: string | null, crisisResourcesShown: boolean): Promise<void>;
    saveReceiverReflection(apologyId: string, emotionSelected: string, privateReflectionText: string | null, actionTaken: string): Promise<boolean>;
    saveVeilVoiceSettings(voice_enabled: boolean, after_voice_dump: boolean, after_text_dump: boolean, after_silent_dump: boolean, morning_follow_up: boolean, carrying_awareness: boolean, after_checkin: boolean, onboarding_completed: boolean): Promise<void>;
    scheduleApology(apologyId: string, recipientUserId: Principal | null, recipientType: string, recipientContact: string | null, deliveryTime: bigint): Promise<boolean>;
    sendApologyNow(apologyId: string, recipientUserId: Principal | null, recipientType: string, recipientContact: string | null): Promise<boolean>;
    updateApologyContent(apologyId: string, content: string, editLevel: string): Promise<boolean>;
    createConfession(mode: string, content: string, wordCount: bigint, hadVoiceComponent: boolean, witnessUserId: Principal | null, crisisSignalDetected: boolean, crisisResourcesShown: boolean): Promise<string>;
    getConfessions(): Promise<Array<Record<string, unknown>>>;
    saveWitnessResponse(confessionId: string, responseType: string): Promise<boolean>;
    deleteConfession(confessionId: string): Promise<boolean>;
    logQuickReleaseSession(platform: string, accessPoint: string, dumpType: Array<string | null>, dumpCompleted: boolean, sessionDuration: Array<number>, returnedTo: string): Promise<string>;
    saveQuickReleaseConfig(platform: string, phrase: string, setupCompleted: boolean): Promise<void>;
    getQuickReleaseConfig(platform: string): Promise<Record<string, unknown> | null>;
}
import type { ApologyEntry as _ApologyEntry, ApologyReceiverReflection as _ApologyReceiverReflection, ApologySchedule as _ApologySchedule, CompanionDump as _CompanionDump, EmotionEntry as _EmotionEntry, EmotionStreakRecord as _EmotionStreakRecord, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VeilVoiceSettings as _VeilVoiceSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acknowledgeApologyOpened(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeApologyOpened(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeApologyOpened(arg0);
            return result;
        }
    }
    async addJournalEntry(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async addReflection(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReflection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReflection(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelApologySchedule(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelApologySchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelApologySchedule(arg0);
            return result;
        }
    }
    async createApology(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: boolean, arg5: string, arg6: string, arg7: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createApology(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApology(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async deleteAllMyApologies(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllMyApologies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllMyApologies();
            return result;
        }
    }
    async deleteJournalEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async deleteUnsentApology(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUnsentApology(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUnsentApology(arg0);
            return result;
        }
    }
    async getAllApologySenderIds(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApologySenderIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApologySenderIds();
            return result;
        }
    }
    async getAllJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJournalEntries();
            return result;
        }
    }
    async getAllReflections(): Promise<Array<Reflection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReflections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReflections();
            return result;
        }
    }
    async getApologyById(arg0: string): Promise<ApologyEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApologyById(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApologyById(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanionDumps(): Promise<Array<CompanionDump>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanionDumps();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanionDumps();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmotionEntries(): Promise<Array<EmotionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmotionEntries();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmotionEntries();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmotionStreakRecord(arg0: string): Promise<EmotionStreakRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmotionStreakRecord(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmotionStreakRecord(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInnerCircle(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInnerCircle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInnerCircle();
            return result;
        }
    }
    async getMyApologies(): Promise<Array<ApologyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApologies();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApologies();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyScheduledApologies(): Promise<Array<ApologySchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyScheduledApologies();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyScheduledApologies();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyUnsentApologies(): Promise<Array<ApologyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyUnsentApologies();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyUnsentApologies();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceivedApologies(): Promise<Array<ApologyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceivedApologies();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceivedApologies();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceiverReflection(arg0: string): Promise<ApologyReceiverReflection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceiverReflection(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceiverReflection(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getTodaysDump(): Promise<CompanionDump | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysDump();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysDump();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVeilVoiceSettings(): Promise<VeilVoiceSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVeilVoiceSettings();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVeilVoiceSettings();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rescheduleApology(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleApology(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleApology(arg0, arg1);
            return result;
        }
    }
    async saveApologyAsUnsent(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveApologyAsUnsent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveApologyAsUnsent(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCompanionDump(arg0: string, arg1: string | null, arg2: bigint | null, arg3: boolean, arg4: boolean, arg5: string, arg6: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCompanionDump(arg0, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCompanionDump(arg0, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async saveEmotionEntry(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string | null, arg5: bigint | null, arg6: string, arg7: boolean, arg8: boolean, arg9: string | null, arg10: boolean, arg11: boolean, arg12: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmotionEntry(arg0, arg1, arg2, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmotionEntry(arg0, arg1, arg2, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n32(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
            return result;
        }
    }
    async saveEmotionStreakRecord(arg0: string, arg1: bigint | null, arg2: string | null, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmotionStreakRecord(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmotionStreakRecord(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async saveReceiverReflection(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReceiverReflection(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReceiverReflection(arg0, arg1, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async saveVeilVoiceSettings(arg0: boolean, arg1: boolean, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVeilVoiceSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVeilVoiceSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async scheduleApology(arg0: string, arg1: Principal | null, arg2: string, arg3: string | null, arg4: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleApology(arg0, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleApology(arg0, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async sendApologyNow(arg0: string, arg1: Principal | null, arg2: string, arg3: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendApologyNow(arg0, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendApologyNow(arg0, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateApologyContent(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApologyContent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApologyContent(arg0, arg1, arg2);
            return result;
        }
    }
    async createConfession(mode: string, content: string, wordCount: bigint, hadVoiceComponent: boolean, witnessUserId: Principal | null, crisisSignalDetected: boolean, crisisResourcesShown: boolean): Promise<string> {
        return (this.actor as any).createConfession(mode, content, wordCount, hadVoiceComponent, witnessUserId ? [witnessUserId] : [], crisisSignalDetected, crisisResourcesShown).catch(() => "");
    }
    async getConfessions(): Promise<Array<Record<string, unknown>>> {
        return (this.actor as any).getConfessions().catch(() => []);
    }
    async saveWitnessResponse(confessionId: string, responseType: string): Promise<boolean> {
        return (this.actor as any).saveWitnessResponse(confessionId, responseType).catch(() => false);
    }
    async deleteConfession(confessionId: string): Promise<boolean> {
        return (this.actor as any).deleteConfession(confessionId).catch(() => false);
    }
    async logQuickReleaseSession(platform: string, accessPoint: string, dumpType: Array<string | null>, dumpCompleted: boolean, sessionDuration: Array<number>, returnedTo: string): Promise<string> {
        return (this.actor as any).logQuickReleaseSession(platform, accessPoint, dumpType, dumpCompleted, sessionDuration, returnedTo).catch(() => "");
    }
    async saveQuickReleaseConfig(platform: string, phrase: string, setupCompleted: boolean): Promise<void> {
        return (this.actor as any).saveQuickReleaseConfig(platform, phrase, setupCompleted).catch(() => undefined);
    }
    async getQuickReleaseConfig(platform: string): Promise<Record<string, unknown> | null> {
        return (this.actor as any).getQuickReleaseConfig(platform).catch(() => null);
    }
}
function from_candid_ApologyEntry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApologyEntry): ApologyEntry {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ApologyReceiverReflection_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApologyReceiverReflection): ApologyReceiverReflection {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ApologySchedule_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApologySchedule): ApologySchedule {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CompanionDump_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanionDump): CompanionDump {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionEntry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionEntry): EmotionEntry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionStreakRecord_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionStreakRecord): EmotionStreakRecord {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmotionStreakRecord]): EmotionStreakRecord | null {
    return value.length === 0 ? null : from_candid_EmotionStreakRecord_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApologyReceiverReflection]): ApologyReceiverReflection | null {
    return value.length === 0 ? null : from_candid_ApologyReceiverReflection_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanionDump]): CompanionDump | null {
    return value.length === 0 ? null : from_candid_CompanionDump_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApologyEntry]): ApologyEntry | null {
    return value.length === 0 ? null : from_candid_ApologyEntry_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VeilVoiceSettings]): VeilVoiceSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    releasedPermanently: boolean;
    voiceDurationSeconds: [] | [bigint];
    contentType: string;
    source: string;
    exhaleMessageShown: string;
    createdAt: _Time;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    streakDay: bigint;
    visibility: string;
    audioStored: boolean;
    textContent: [] | [string];
}): {
    id: string;
    releasedPermanently: boolean;
    voiceDurationSeconds?: bigint;
    contentType: string;
    source: string;
    exhaleMessageShown: string;
    createdAt: Time;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    streakDay: bigint;
    visibility: string;
    audioStored: boolean;
    textContent?: string;
} {
    return {
        id: value.id,
        releasedPermanently: value.releasedPermanently,
        voiceDurationSeconds: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.voiceDurationSeconds)),
        contentType: value.contentType,
        source: value.source,
        exhaleMessageShown: value.exhaleMessageShown,
        createdAt: value.createdAt,
        crisisResourcesShown: value.crisisResourcesShown,
        crisisSignalDetected: value.crisisSignalDetected,
        streakDay: value.streakDay,
        visibility: value.visibility,
        audioStored: value.audioStored,
        textContent: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.textContent))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    emotionType: string;
    aiPromptText: [] | [string];
    customEmotionLabel: [] | [string];
    voiceDurationSeconds: [] | [bigint];
    source: string;
    emotionLabel: string;
    exhaleMessageShown: string;
    createdAt: _Time;
    emoji: string;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    visibilityLevel: string;
    aiPromptShown: boolean;
    textReflection: [] | [string];
    voiceOverrideApplied: boolean;
}): {
    id: string;
    emotionType: string;
    aiPromptText?: string;
    customEmotionLabel?: string;
    voiceDurationSeconds?: bigint;
    source: string;
    emotionLabel: string;
    exhaleMessageShown: string;
    createdAt: Time;
    emoji: string;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    visibilityLevel: string;
    aiPromptShown: boolean;
    textReflection?: string;
    voiceOverrideApplied: boolean;
} {
    return {
        id: value.id,
        emotionType: value.emotionType,
        aiPromptText: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.aiPromptText)),
        customEmotionLabel: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.customEmotionLabel)),
        voiceDurationSeconds: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.voiceDurationSeconds)),
        source: value.source,
        emotionLabel: value.emotionLabel,
        exhaleMessageShown: value.exhaleMessageShown,
        createdAt: value.createdAt,
        emoji: value.emoji,
        crisisResourcesShown: value.crisisResourcesShown,
        crisisSignalDetected: value.crisisSignalDetected,
        visibilityLevel: value.visibilityLevel,
        aiPromptShown: value.aiPromptShown,
        textReflection: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.textReflection)),
        voiceOverrideApplied: value.voiceOverrideApplied
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    acknowledgmentType: [] | [string];
    emotionType: string;
    lastAwarenessShownAt: [] | [bigint];
    updatedAt: bigint;
    crisisResourcesShown: boolean;
    lastAwarenessMilestone: [] | [bigint];
}): {
    acknowledgmentType?: string;
    emotionType: string;
    lastAwarenessShownAt?: bigint;
    updatedAt: bigint;
    crisisResourcesShown: boolean;
    lastAwarenessMilestone?: bigint;
} {
    return {
        acknowledgmentType: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.acknowledgmentType)),
        emotionType: value.emotionType,
        lastAwarenessShownAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.lastAwarenessShownAt)),
        updatedAt: value.updatedAt,
        crisisResourcesShown: value.crisisResourcesShown,
        lastAwarenessMilestone: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.lastAwarenessMilestone))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    deliveredAt: [] | [bigint];
    apologyId: string;
    rescheduleCount: bigint;
    cancelledAt: [] | [bigint];
    scheduledDeliveryTime: bigint;
    reminderSent: boolean;
    reminderSentAt: [] | [bigint];
    senderUserId: Principal;
}): {
    id: string;
    status: string;
    deliveredAt?: bigint;
    apologyId: string;
    rescheduleCount: bigint;
    cancelledAt?: bigint;
    scheduledDeliveryTime: bigint;
    reminderSent: boolean;
    reminderSentAt?: bigint;
    senderUserId: Principal;
} {
    return {
        id: value.id,
        status: value.status,
        deliveredAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.deliveredAt)),
        apologyId: value.apologyId,
        rescheduleCount: value.rescheduleCount,
        cancelledAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.cancelledAt)),
        scheduledDeliveryTime: value.scheduledDeliveryTime,
        reminderSent: value.reminderSent,
        reminderSentAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.reminderSentAt)),
        senderUserId: value.senderUserId
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    completedAt: [] | [bigint];
    emotionSelected: string;
    receiverUserId: Principal;
    journalEntryId: [] | [string];
    createdAt: bigint;
    privateReflectionText: [] | [string];
    apologyId: string;
    actionTaken: string;
    reflectionComplete: boolean;
}): {
    id: string;
    completedAt?: bigint;
    emotionSelected: string;
    receiverUserId: Principal;
    journalEntryId?: string;
    createdAt: bigint;
    privateReflectionText?: string;
    apologyId: string;
    actionTaken: string;
    reflectionComplete: boolean;
} {
    return {
        id: value.id,
        completedAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.completedAt)),
        emotionSelected: value.emotionSelected,
        receiverUserId: value.receiverUserId,
        journalEntryId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.journalEntryId)),
        createdAt: value.createdAt,
        privateReflectionText: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.privateReflectionText)),
        apologyId: value.apologyId,
        actionTaken: value.actionTaken,
        reflectionComplete: value.reflectionComplete
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    editLevel: string;
    nonVeilToken: [] | [string];
    signature: string;
    emotionType: string;
    sharedSilenceTriggered: boolean;
    content: string;
    deliveredAt: [] | [bigint];
    acknowledgedAt: [] | [bigint];
    aiVersionUsed: string;
    source: string;
    createdAt: bigint;
    recipientContact: [] | [string];
    aiAssisted: boolean;
    isAnonymous: boolean;
    deliveryMethod: string;
    deliveryTime: [] | [bigint];
    recipientUserId: [] | [Principal];
    rescheduleCount: bigint;
    crisisSignalDetected: boolean;
    visibility: string;
    recipientType: string;
    senderUserId: Principal;
    nonVeilTokenExpires: [] | [bigint];
    openedAt: [] | [bigint];
}): {
    id: string;
    status: string;
    editLevel: string;
    nonVeilToken?: string;
    signature: string;
    emotionType: string;
    sharedSilenceTriggered: boolean;
    content: string;
    deliveredAt?: bigint;
    acknowledgedAt?: bigint;
    aiVersionUsed: string;
    source: string;
    createdAt: bigint;
    recipientContact?: string;
    aiAssisted: boolean;
    isAnonymous: boolean;
    deliveryMethod: string;
    deliveryTime?: bigint;
    recipientUserId?: Principal;
    rescheduleCount: bigint;
    crisisSignalDetected: boolean;
    visibility: string;
    recipientType: string;
    senderUserId: Principal;
    nonVeilTokenExpires?: bigint;
    openedAt?: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        editLevel: value.editLevel,
        nonVeilToken: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.nonVeilToken)),
        signature: value.signature,
        emotionType: value.emotionType,
        sharedSilenceTriggered: value.sharedSilenceTriggered,
        content: value.content,
        deliveredAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.deliveredAt)),
        acknowledgedAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.acknowledgedAt)),
        aiVersionUsed: value.aiVersionUsed,
        source: value.source,
        createdAt: value.createdAt,
        recipientContact: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.recipientContact)),
        aiAssisted: value.aiAssisted,
        isAnonymous: value.isAnonymous,
        deliveryMethod: value.deliveryMethod,
        deliveryTime: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.deliveryTime)),
        recipientUserId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.recipientUserId)),
        rescheduleCount: value.rescheduleCount,
        crisisSignalDetected: value.crisisSignalDetected,
        visibility: value.visibility,
        recipientType: value.recipientType,
        senderUserId: value.senderUserId,
        nonVeilTokenExpires: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.nonVeilTokenExpires)),
        openedAt: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.openedAt))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompanionDump>): Array<CompanionDump> {
    return value.map((x)=>from_candid_CompanionDump_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmotionEntry>): Array<EmotionEntry> {
    return value.map((x)=>from_candid_EmotionEntry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApologyEntry>): Array<ApologyEntry> {
    return value.map((x)=>from_candid_ApologyEntry_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApologySchedule>): Array<ApologySchedule> {
    return value.map((x)=>from_candid_ApologySchedule_n24(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
