/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ApologySchedule {
    id: string;
    status: string;
    deliveredAt?: bigint;
    apologyId: string;
    rescheduleCount: bigint;
    cancelledAt?: bigint;
    scheduledDeliveryTime: bigint;
    reminderSent: boolean;
    reminderSentAt?: bigint;
    senderUserId: Principal;
}
export type Time = bigint;
export interface LoveLetter {
    id: string;
    status: string;
    editLevel: string;
    nonVeilToken?: string;
    signature: string;
    deliveredAt?: bigint;
    aiVersionUsed: string;
    visualStyle: string;
    feltAt?: bigint;
    wordCount: bigint;
    journalEntryId?: string;
    createdAt: bigint;
    recipientContact?: string;
    aiAssisted: boolean;
    isAnonymous: boolean;
    openingLine: string;
    letterType: string;
    deliveryMethod: string;
    onThisDaySurfaced: boolean;
    deliveryTime?: bigint;
    recipientUserId?: Principal;
    crisisSignalDetected: boolean;
    closingLine: string;
    bodyText: string;
    visibility: string;
    recipientType: string;
    sharedWarmthTriggered: boolean;
    senderUserId: Principal;
    nonVeilTokenExpires?: bigint;
    openedAt?: bigint;
}
export interface Confession {
    id: string;
    apologyCreatedAfter: boolean;
    witnessResponseDelivered: boolean;
    content: string;
    deletionRequested: boolean;
    wordCount: bigint;
    userId: Principal;
    mode: string;
    createdAt: bigint;
    witnessOpened: boolean;
    onThisDaySurfaced: boolean;
    witnessResponse?: string;
    witnessUserId?: Principal;
    witnessNotified: boolean;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    hadVoiceComponent: boolean;
    apologyBridgeShown: boolean;
}
export interface Stats {
    totalEntries: bigint;
    moodFrequency: Array<[string, bigint]>;
    currentStreak: bigint;
}
export interface Reflection {
    id: string;
    response: string;
    timestamp: Time;
    prompt: string;
}
export interface ApologyReceiverReflection {
    id: string;
    completedAt?: bigint;
    emotionSelected: string;
    receiverUserId: Principal;
    journalEntryId?: string;
    createdAt: bigint;
    privateReflectionText?: string;
    apologyId: string;
    actionTaken: string;
    reflectionComplete: boolean;
}
export interface VeilVoiceSettings {
    moments_enabled: VeilVoiceMomentsEnabled;
    onboarding_completed: boolean;
    voice_enabled: boolean;
}
export interface VeilVoiceMomentsEnabled {
    after_checkin: boolean;
    carrying_awareness: boolean;
    after_silent_dump: boolean;
    after_text_dump: boolean;
    after_voice_dump: boolean;
    morning_follow_up: boolean;
}
export interface SurfaceDelivery {
    id: string;
    deliveredAt?: Time;
    surfaceType: string;
    userId: Principal;
    createdAt: Time;
    deliveryStatus: string;
    scheduledForSessionAfter: Time;
    signalId: string;
    dismissed: boolean;
}
export interface SignificanceSignal {
    id: string;
    surfaceTypeUsed?: string;
    significanceScore: number;
    eligibleForReturnAfter: Time;
    userId: Principal;
    usedInSurface: boolean;
    rawEmotionIntensity: bigint;
    createdAt: Time;
    contextSnapshot: string;
    signalIntensity: number;
    rawEmotionType: string;
    returnedAt?: Time;
    signalType: string;
}
export interface JournalEntry {
    id: string;
    title: string;
    body: string;
    mood: string;
    timestamp: Time;
}
export interface ApologyEntry {
    id: string;
    status: string;
    editLevel: string;
    nonVeilToken?: string;
    signature: string;
    emotionType: string;
    sharedSilenceTriggered: boolean;
    content: string;
    deliveredAt?: bigint;
    acknowledgedAt?: bigint;
    aiVersionUsed: string;
    source: string;
    createdAt: bigint;
    recipientContact?: string;
    aiAssisted: boolean;
    isAnonymous: boolean;
    deliveryMethod: string;
    deliveryTime?: bigint;
    recipientUserId?: Principal;
    rescheduleCount: bigint;
    crisisSignalDetected: boolean;
    visibility: string;
    recipientType: string;
    senderUserId: Principal;
    nonVeilTokenExpires?: bigint;
    openedAt?: bigint;
}
export interface QuickReleaseConfig {
    userId: Principal;
    platform: string;
    activationCount: bigint;
    setupDate?: bigint;
    setupCompleted: boolean;
    lastActivatedAt?: bigint;
    phrase: string;
}
export interface EmotionEntry {
    id: string;
    emotionType: string;
    aiPromptText?: string;
    customEmotionLabel?: string;
    voiceDurationSeconds?: bigint;
    source: string;
    emotionLabel: string;
    exhaleMessageShown: string;
    createdAt: Time;
    emoji: string;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    visibilityLevel: string;
    aiPromptShown: boolean;
    textReflection?: string;
    voiceOverrideApplied: boolean;
}
export interface SignificantMomentsSettings {
    returnLetterEnabled: boolean;
    memoryMirrorEnabled: boolean;
    becomingMomentEnabled: boolean;
    userId: Principal;
    createdAt: Time;
    enabled: boolean;
    updatedAt: Time;
    milestoneHoldEnabled: boolean;
    frequency: string;
    whisperEnabled: boolean;
    peakSealEnabled: boolean;
}
export interface EmotionStreakRecord {
    acknowledgmentType?: string;
    emotionType: string;
    lastAwarenessShownAt?: bigint;
    updatedAt: bigint;
    crisisResourcesShown: boolean;
    lastAwarenessMilestone?: bigint;
}
export interface CompanionDump {
    id: string;
    releasedPermanently: boolean;
    voiceDurationSeconds?: bigint;
    contentType: string;
    source: string;
    exhaleMessageShown: string;
    createdAt: Time;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    streakDay: bigint;
    visibility: string;
    audioStored: boolean;
    textContent?: string;
}
export interface UserProfile {
    displayName: string;
}
export interface FutureLetterDelivery {
    id: string;
    writtenAt: Time;
    deliveredAt?: Time;
    deliveryTriggerJson: string;
    userId: Principal;
    deliveryStatus: string;
    overrideDate: Time;
    letterId: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acknowledgeApologyOpened(apologyId: string): Promise<boolean>;
    addJournalEntry(title: string, body: string, mood: string): Promise<string>;
    addReflection(prompt: string, response: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelApologySchedule(apologyId: string): Promise<boolean>;
    createApology(content: string, signature: string, emotionType: string, isAnonymous: boolean, aiAssisted: boolean, aiVersionUsed: string, source: string, crisisSignalDetected: boolean): Promise<string>;
    createConfession(mode: string, content: string, wordCount: bigint, hadVoiceComponent: boolean, witnessUserId: Principal | null, crisisSignalDetected: boolean, crisisResourcesShown: boolean): Promise<string>;
    createLoveLetter(letterType: string, openingLine: string, bodyText: string, closingLine: string, signature: string, wordCount: bigint, visualStyle: string, isAnonymous: boolean, aiAssisted: boolean, aiVersionUsed: string, editLevel: string, deliveryMethod: string, deliveryTime: bigint | null, recipientType: string, recipientContact: string | null, nonVeilToken: string | null, nonVeilTokenExpires: bigint | null, crisisSignalDetected: boolean): Promise<string>;
    deleteAllMyApologies(): Promise<boolean>;
    deleteAllMySignificanceData(): Promise<boolean>;
    deleteConfession(confessionId: string): Promise<boolean>;
    deleteJournalEntry(id: string): Promise<void>;
    deleteUnsentApology(apologyId: string): Promise<boolean>;
    dismissSurfaceDelivery(id: string): Promise<boolean>;
    getAllApologySenderIds(): Promise<Array<Principal>>;
    getAllJournalEntries(): Promise<Array<JournalEntry>>;
    getAllReflections(): Promise<Array<Reflection>>;
    getApologyById(apologyId: string): Promise<ApologyEntry | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanionDumps(): Promise<Array<CompanionDump>>;
    getConfessions(): Promise<Array<Confession>>;
    getEmotionEntries(): Promise<Array<EmotionEntry>>;
    getEmotionStreakRecord(emotionType: string): Promise<EmotionStreakRecord | null>;
    getFutureLetterDeliveries(): Promise<Array<FutureLetterDelivery>>;
    getInnerCircle(): Promise<Array<Principal>>;
    getLoveLettersBySender(): Promise<Array<LoveLetter>>;
    getMyApologies(): Promise<Array<ApologyEntry>>;
    getMyScheduledApologies(): Promise<Array<ApologySchedule>>;
    getMyUnsentApologies(): Promise<Array<ApologyEntry>>;
    getQuickReleaseConfig(platform: string): Promise<QuickReleaseConfig | null>;
    getReceivedApologies(): Promise<Array<ApologyEntry>>;
    getReceiverReflection(apologyId: string): Promise<ApologyReceiverReflection | null>;
    getSignificanceSignals(): Promise<Array<SignificanceSignal>>;
    getSignificantMomentsSettings(): Promise<SignificantMomentsSettings | null>;
    getStats(): Promise<Stats>;
    getSurfaceDeliveries(): Promise<Array<SurfaceDelivery>>;
    getTodaysDump(): Promise<CompanionDump | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVeilVoiceSettings(): Promise<VeilVoiceSettings | null>;
    isCallerAdmin(): Promise<boolean>;
    logQuickReleaseSession(platform: string, accessPoint: string, dumpType: string | null, dumpCompleted: boolean, sessionDuration: bigint | null, returnedTo: string): Promise<string>;
    markFutureLetterDelivered(id: string): Promise<boolean>;
    markSurfaceDelivered(id: string, surfaceType: string): Promise<boolean>;
    recordSignificanceSignal(signalType: string, signalIntensity: number, rawEmotionType: string, rawEmotionIntensity: bigint, contextSnapshot: string, eligibleForReturnAfterDays: bigint): Promise<string>;
    recordSurfaceDelivery(signalId: string, surfaceType: string, scheduledForSessionAfter: Time): Promise<string>;
    rescheduleApology(apologyId: string, newDeliveryTime: bigint): Promise<boolean>;
    saveApologyAsUnsent(apologyId: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCompanionDump(contentType: string, textContent: string | null, voiceDurationSeconds: bigint | null, crisisSignalDetected: boolean, crisisResourcesShown: boolean, exhaleMessageShown: string, streakDay: bigint): Promise<string>;
    saveEmotionEntry(emotionType: string, emotionLabel: string, emoji: string, customEmotionLabel: string | null, textReflection: string | null, voiceDurationSeconds: bigint | null, visibilityLevel: string, voiceOverrideApplied: boolean, aiPromptShown: boolean, aiPromptText: string | null, crisisSignalDetected: boolean, crisisResourcesShown: boolean, exhaleMessageShown: string): Promise<string>;
    saveEmotionStreakRecord(emotionType: string, lastAwarenessMilestone: bigint | null, acknowledgmentType: string | null, crisisResourcesShown: boolean): Promise<void>;
    saveFutureLetterDelivery(letterId: string, deliveryTriggerJson: string, overrideDays: bigint): Promise<string>;
    saveLoveLetterReaction(letterId: string, reactionType: string, replyLetterId: string | null): Promise<boolean>;
    saveQuickReleaseConfig(platform: string, phrase: string, setupCompleted: boolean): Promise<boolean>;
    saveReceiverReflection(apologyId: string, emotionSelected: string, privateReflectionText: string | null, actionTaken: string): Promise<boolean>;
    saveSignificantMomentsSettings(enabled: boolean, whisperEnabled: boolean, memoryMirrorEnabled: boolean, returnLetterEnabled: boolean, becomingMomentEnabled: boolean, milestoneHoldEnabled: boolean, peakSealEnabled: boolean, frequency: string): Promise<void>;
    saveVeilVoiceSettings(voice_enabled: boolean, after_voice_dump: boolean, after_text_dump: boolean, after_silent_dump: boolean, morning_follow_up: boolean, carrying_awareness: boolean, after_checkin: boolean, onboarding_completed: boolean): Promise<void>;
    saveWitnessResponse(confessionId: string, responseType: string): Promise<boolean>;
    scheduleApology(apologyId: string, recipientUserId: Principal | null, recipientType: string, recipientContact: string | null, deliveryTime: bigint): Promise<boolean>;
    scheduleLoveLetter(letterId: string, scheduledDeliveryTime: bigint, deliveryType: string): Promise<boolean>;
    sendApologyNow(apologyId: string, recipientUserId: Principal | null, recipientType: string, recipientContact: string | null): Promise<boolean>;
    updateApologyContent(apologyId: string, content: string, editLevel: string): Promise<boolean>;
    updateSignificanceScore(id: string, score: number): Promise<boolean>;
}
import type { ApologyEntry as _ApologyEntry, ApologyReceiverReflection as _ApologyReceiverReflection, ApologySchedule as _ApologySchedule, CompanionDump as _CompanionDump, Confession as _Confession, EmotionEntry as _EmotionEntry, EmotionStreakRecord as _EmotionStreakRecord, FutureLetterDelivery as _FutureLetterDelivery, LoveLetter as _LoveLetter, QuickReleaseConfig as _QuickReleaseConfig, SignificanceSignal as _SignificanceSignal, SignificantMomentsSettings as _SignificantMomentsSettings, SurfaceDelivery as _SurfaceDelivery, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VeilVoiceSettings as _VeilVoiceSettings } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acknowledgeApologyOpened(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.acknowledgeApologyOpened(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acknowledgeApologyOpened(arg0);
            return result;
        }
    }
    async addJournalEntry(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async addReflection(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReflection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReflection(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelApologySchedule(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelApologySchedule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelApologySchedule(arg0);
            return result;
        }
    }
    async createApology(arg0: string, arg1: string, arg2: string, arg3: boolean, arg4: boolean, arg5: string, arg6: string, arg7: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createApology(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createApology(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async createConfession(arg0: string, arg1: string, arg2: bigint, arg3: boolean, arg4: Principal | null, arg5: boolean, arg6: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createConfession(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConfession(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async createLoveLetter(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: string, arg7: boolean, arg8: boolean, arg9: string, arg10: string, arg11: string, arg12: bigint | null, arg13: string, arg14: string | null, arg15: string | null, arg16: bigint | null, arg17: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createLoveLetter(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg12), arg13, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg14), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg15), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg16), arg17);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLoveLetter(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg12), arg13, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg14), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg15), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg16), arg17);
            return result;
        }
    }
    async deleteAllMyApologies(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllMyApologies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllMyApologies();
            return result;
        }
    }
    async deleteAllMySignificanceData(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllMySignificanceData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllMySignificanceData();
            return result;
        }
    }
    async deleteConfession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteConfession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteConfession(arg0);
            return result;
        }
    }
    async deleteJournalEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async deleteUnsentApology(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUnsentApology(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUnsentApology(arg0);
            return result;
        }
    }
    async dismissSurfaceDelivery(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissSurfaceDelivery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissSurfaceDelivery(arg0);
            return result;
        }
    }
    async getAllApologySenderIds(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApologySenderIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApologySenderIds();
            return result;
        }
    }
    async getAllJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJournalEntries();
            return result;
        }
    }
    async getAllReflections(): Promise<Array<Reflection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReflections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReflections();
            return result;
        }
    }
    async getApologyById(arg0: string): Promise<ApologyEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApologyById(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApologyById(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanionDumps(): Promise<Array<CompanionDump>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanionDumps();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanionDumps();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConfessions(): Promise<Array<Confession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConfessions();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConfessions();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmotionEntries(): Promise<Array<EmotionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmotionEntries();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmotionEntries();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmotionStreakRecord(arg0: string): Promise<EmotionStreakRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmotionStreakRecord(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmotionStreakRecord(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFutureLetterDeliveries(): Promise<Array<FutureLetterDelivery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFutureLetterDeliveries();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFutureLetterDeliveries();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInnerCircle(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInnerCircle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInnerCircle();
            return result;
        }
    }
    async getLoveLettersBySender(): Promise<Array<LoveLetter>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLoveLettersBySender();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLoveLettersBySender();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApologies(): Promise<Array<ApologyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApologies();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApologies();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyScheduledApologies(): Promise<Array<ApologySchedule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyScheduledApologies();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyScheduledApologies();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyUnsentApologies(): Promise<Array<ApologyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyUnsentApologies();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyUnsentApologies();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuickReleaseConfig(arg0: string): Promise<QuickReleaseConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuickReleaseConfig(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuickReleaseConfig(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceivedApologies(): Promise<Array<ApologyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceivedApologies();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceivedApologies();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReceiverReflection(arg0: string): Promise<ApologyReceiverReflection | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReceiverReflection(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReceiverReflection(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignificanceSignals(): Promise<Array<SignificanceSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignificanceSignals();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignificanceSignals();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignificantMomentsSettings(): Promise<SignificantMomentsSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignificantMomentsSettings();
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignificantMomentsSettings();
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getSurfaceDeliveries(): Promise<Array<SurfaceDelivery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSurfaceDeliveries();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSurfaceDeliveries();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodaysDump(): Promise<CompanionDump | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodaysDump();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodaysDump();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVeilVoiceSettings(): Promise<VeilVoiceSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVeilVoiceSettings();
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVeilVoiceSettings();
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logQuickReleaseSession(arg0: string, arg1: string, arg2: string | null, arg3: boolean, arg4: bigint | null, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.logQuickReleaseSession(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logQuickReleaseSession(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async markFutureLetterDelivered(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markFutureLetterDelivered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markFutureLetterDelivered(arg0);
            return result;
        }
    }
    async markSurfaceDelivered(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markSurfaceDelivered(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSurfaceDelivered(arg0, arg1);
            return result;
        }
    }
    async recordSignificanceSignal(arg0: string, arg1: number, arg2: string, arg3: bigint, arg4: string, arg5: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSignificanceSignal(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSignificanceSignal(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async recordSurfaceDelivery(arg0: string, arg1: string, arg2: Time): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.recordSurfaceDelivery(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordSurfaceDelivery(arg0, arg1, arg2);
            return result;
        }
    }
    async rescheduleApology(arg0: string, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleApology(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleApology(arg0, arg1);
            return result;
        }
    }
    async saveApologyAsUnsent(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveApologyAsUnsent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveApologyAsUnsent(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCompanionDump(arg0: string, arg1: string | null, arg2: bigint | null, arg3: boolean, arg4: boolean, arg5: string, arg6: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCompanionDump(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCompanionDump(arg0, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async saveEmotionEntry(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string | null, arg5: bigint | null, arg6: string, arg7: boolean, arg8: boolean, arg9: string | null, arg10: boolean, arg11: boolean, arg12: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmotionEntry(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmotionEntry(arg0, arg1, arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12);
            return result;
        }
    }
    async saveEmotionStreakRecord(arg0: string, arg1: bigint | null, arg2: string | null, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmotionStreakRecord(arg0, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmotionStreakRecord(arg0, to_candid_opt_n54(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async saveFutureLetterDelivery(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFutureLetterDelivery(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFutureLetterDelivery(arg0, arg1, arg2);
            return result;
        }
    }
    async saveLoveLetterReaction(arg0: string, arg1: string, arg2: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLoveLetterReaction(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveLoveLetterReaction(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveQuickReleaseConfig(arg0: string, arg1: string, arg2: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveQuickReleaseConfig(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveQuickReleaseConfig(arg0, arg1, arg2);
            return result;
        }
    }
    async saveReceiverReflection(arg0: string, arg1: string, arg2: string | null, arg3: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReceiverReflection(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReceiverReflection(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async saveSignificantMomentsSettings(arg0: boolean, arg1: boolean, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSignificantMomentsSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSignificantMomentsSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async saveVeilVoiceSettings(arg0: boolean, arg1: boolean, arg2: boolean, arg3: boolean, arg4: boolean, arg5: boolean, arg6: boolean, arg7: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVeilVoiceSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVeilVoiceSettings(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async saveWitnessResponse(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveWitnessResponse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveWitnessResponse(arg0, arg1);
            return result;
        }
    }
    async scheduleApology(arg0: string, arg1: Principal | null, arg2: string, arg3: string | null, arg4: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleApology(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleApology(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async scheduleLoveLetter(arg0: string, arg1: bigint, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleLoveLetter(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleLoveLetter(arg0, arg1, arg2);
            return result;
        }
    }
    async sendApologyNow(arg0: string, arg1: Principal | null, arg2: string, arg3: string | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendApologyNow(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendApologyNow(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateApologyContent(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApologyContent(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApologyContent(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSignificanceScore(arg0: string, arg1: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSignificanceScore(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSignificanceScore(arg0, arg1);
            return result;
        }
    }
}
function from_candid_ApologyEntry_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApologyEntry): ApologyEntry {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ApologyReceiverReflection_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApologyReceiverReflection): ApologyReceiverReflection {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_ApologySchedule_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApologySchedule): ApologySchedule {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_CompanionDump_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanionDump): CompanionDump {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Confession_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Confession): Confession {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionEntry_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionEntry): EmotionEntry {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionStreakRecord_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionStreakRecord): EmotionStreakRecord {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_FutureLetterDelivery_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FutureLetterDelivery): FutureLetterDelivery {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_LoveLetter_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoveLetter): LoveLetter {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_QuickReleaseConfig_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuickReleaseConfig): QuickReleaseConfig {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_SignificanceSignal_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignificanceSignal): SignificanceSignal {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_SurfaceDelivery_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SurfaceDelivery): SurfaceDelivery {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmotionStreakRecord]): EmotionStreakRecord | null {
    return value.length === 0 ? null : from_candid_EmotionStreakRecord_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuickReleaseConfig]): QuickReleaseConfig | null {
    return value.length === 0 ? null : from_candid_QuickReleaseConfig_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApologyReceiverReflection]): ApologyReceiverReflection | null {
    return value.length === 0 ? null : from_candid_ApologyReceiverReflection_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SignificantMomentsSettings]): SignificantMomentsSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanionDump]): CompanionDump | null {
    return value.length === 0 ? null : from_candid_CompanionDump_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VeilVoiceSettings]): VeilVoiceSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApologyEntry]): ApologyEntry | null {
    return value.length === 0 ? null : from_candid_ApologyEntry_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    releasedPermanently: boolean;
    voiceDurationSeconds: [] | [bigint];
    contentType: string;
    source: string;
    exhaleMessageShown: string;
    createdAt: _Time;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    streakDay: bigint;
    visibility: string;
    audioStored: boolean;
    textContent: [] | [string];
}): {
    id: string;
    releasedPermanently: boolean;
    voiceDurationSeconds?: bigint;
    contentType: string;
    source: string;
    exhaleMessageShown: string;
    createdAt: Time;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    streakDay: bigint;
    visibility: string;
    audioStored: boolean;
    textContent?: string;
} {
    return {
        id: value.id,
        releasedPermanently: value.releasedPermanently,
        voiceDurationSeconds: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.voiceDurationSeconds)),
        contentType: value.contentType,
        source: value.source,
        exhaleMessageShown: value.exhaleMessageShown,
        createdAt: value.createdAt,
        crisisResourcesShown: value.crisisResourcesShown,
        crisisSignalDetected: value.crisisSignalDetected,
        streakDay: value.streakDay,
        visibility: value.visibility,
        audioStored: value.audioStored,
        textContent: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.textContent))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    apologyCreatedAfter: boolean;
    witnessResponseDelivered: boolean;
    content: string;
    deletionRequested: boolean;
    wordCount: bigint;
    userId: Principal;
    mode: string;
    createdAt: bigint;
    witnessOpened: boolean;
    onThisDaySurfaced: boolean;
    witnessResponse: [] | [string];
    witnessUserId: [] | [Principal];
    witnessNotified: boolean;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    hadVoiceComponent: boolean;
    apologyBridgeShown: boolean;
}): {
    id: string;
    apologyCreatedAfter: boolean;
    witnessResponseDelivered: boolean;
    content: string;
    deletionRequested: boolean;
    wordCount: bigint;
    userId: Principal;
    mode: string;
    createdAt: bigint;
    witnessOpened: boolean;
    onThisDaySurfaced: boolean;
    witnessResponse?: string;
    witnessUserId?: Principal;
    witnessNotified: boolean;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    hadVoiceComponent: boolean;
    apologyBridgeShown: boolean;
} {
    return {
        id: value.id,
        apologyCreatedAfter: value.apologyCreatedAfter,
        witnessResponseDelivered: value.witnessResponseDelivered,
        content: value.content,
        deletionRequested: value.deletionRequested,
        wordCount: value.wordCount,
        userId: value.userId,
        mode: value.mode,
        createdAt: value.createdAt,
        witnessOpened: value.witnessOpened,
        onThisDaySurfaced: value.onThisDaySurfaced,
        witnessResponse: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.witnessResponse)),
        witnessUserId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.witnessUserId)),
        witnessNotified: value.witnessNotified,
        crisisResourcesShown: value.crisisResourcesShown,
        crisisSignalDetected: value.crisisSignalDetected,
        hadVoiceComponent: value.hadVoiceComponent,
        apologyBridgeShown: value.apologyBridgeShown
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    emotionType: string;
    aiPromptText: [] | [string];
    customEmotionLabel: [] | [string];
    voiceDurationSeconds: [] | [bigint];
    source: string;
    emotionLabel: string;
    exhaleMessageShown: string;
    createdAt: _Time;
    emoji: string;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    visibilityLevel: string;
    aiPromptShown: boolean;
    textReflection: [] | [string];
    voiceOverrideApplied: boolean;
}): {
    id: string;
    emotionType: string;
    aiPromptText?: string;
    customEmotionLabel?: string;
    voiceDurationSeconds?: bigint;
    source: string;
    emotionLabel: string;
    exhaleMessageShown: string;
    createdAt: Time;
    emoji: string;
    crisisResourcesShown: boolean;
    crisisSignalDetected: boolean;
    visibilityLevel: string;
    aiPromptShown: boolean;
    textReflection?: string;
    voiceOverrideApplied: boolean;
} {
    return {
        id: value.id,
        emotionType: value.emotionType,
        aiPromptText: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.aiPromptText)),
        customEmotionLabel: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.customEmotionLabel)),
        voiceDurationSeconds: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.voiceDurationSeconds)),
        source: value.source,
        emotionLabel: value.emotionLabel,
        exhaleMessageShown: value.exhaleMessageShown,
        createdAt: value.createdAt,
        emoji: value.emoji,
        crisisResourcesShown: value.crisisResourcesShown,
        crisisSignalDetected: value.crisisSignalDetected,
        visibilityLevel: value.visibilityLevel,
        aiPromptShown: value.aiPromptShown,
        textReflection: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.textReflection)),
        voiceOverrideApplied: value.voiceOverrideApplied
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    acknowledgmentType: [] | [string];
    emotionType: string;
    lastAwarenessShownAt: [] | [bigint];
    updatedAt: bigint;
    crisisResourcesShown: boolean;
    lastAwarenessMilestone: [] | [bigint];
}): {
    acknowledgmentType?: string;
    emotionType: string;
    lastAwarenessShownAt?: bigint;
    updatedAt: bigint;
    crisisResourcesShown: boolean;
    lastAwarenessMilestone?: bigint;
} {
    return {
        acknowledgmentType: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.acknowledgmentType)),
        emotionType: value.emotionType,
        lastAwarenessShownAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.lastAwarenessShownAt)),
        updatedAt: value.updatedAt,
        crisisResourcesShown: value.crisisResourcesShown,
        lastAwarenessMilestone: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.lastAwarenessMilestone))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    writtenAt: _Time;
    deliveredAt: [] | [_Time];
    deliveryTriggerJson: string;
    userId: Principal;
    deliveryStatus: string;
    overrideDate: _Time;
    letterId: string;
}): {
    id: string;
    writtenAt: Time;
    deliveredAt?: Time;
    deliveryTriggerJson: string;
    userId: Principal;
    deliveryStatus: string;
    overrideDate: Time;
    letterId: string;
} {
    return {
        id: value.id,
        writtenAt: value.writtenAt,
        deliveredAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.deliveredAt)),
        deliveryTriggerJson: value.deliveryTriggerJson,
        userId: value.userId,
        deliveryStatus: value.deliveryStatus,
        overrideDate: value.overrideDate,
        letterId: value.letterId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    editLevel: string;
    nonVeilToken: [] | [string];
    signature: string;
    deliveredAt: [] | [bigint];
    aiVersionUsed: string;
    visualStyle: string;
    feltAt: [] | [bigint];
    wordCount: bigint;
    journalEntryId: [] | [string];
    createdAt: bigint;
    recipientContact: [] | [string];
    aiAssisted: boolean;
    isAnonymous: boolean;
    openingLine: string;
    letterType: string;
    deliveryMethod: string;
    onThisDaySurfaced: boolean;
    deliveryTime: [] | [bigint];
    recipientUserId: [] | [Principal];
    crisisSignalDetected: boolean;
    closingLine: string;
    bodyText: string;
    visibility: string;
    recipientType: string;
    sharedWarmthTriggered: boolean;
    senderUserId: Principal;
    nonVeilTokenExpires: [] | [bigint];
    openedAt: [] | [bigint];
}): {
    id: string;
    status: string;
    editLevel: string;
    nonVeilToken?: string;
    signature: string;
    deliveredAt?: bigint;
    aiVersionUsed: string;
    visualStyle: string;
    feltAt?: bigint;
    wordCount: bigint;
    journalEntryId?: string;
    createdAt: bigint;
    recipientContact?: string;
    aiAssisted: boolean;
    isAnonymous: boolean;
    openingLine: string;
    letterType: string;
    deliveryMethod: string;
    onThisDaySurfaced: boolean;
    deliveryTime?: bigint;
    recipientUserId?: Principal;
    crisisSignalDetected: boolean;
    closingLine: string;
    bodyText: string;
    visibility: string;
    recipientType: string;
    sharedWarmthTriggered: boolean;
    senderUserId: Principal;
    nonVeilTokenExpires?: bigint;
    openedAt?: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        editLevel: value.editLevel,
        nonVeilToken: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.nonVeilToken)),
        signature: value.signature,
        deliveredAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deliveredAt)),
        aiVersionUsed: value.aiVersionUsed,
        visualStyle: value.visualStyle,
        feltAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.feltAt)),
        wordCount: value.wordCount,
        journalEntryId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.journalEntryId)),
        createdAt: value.createdAt,
        recipientContact: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.recipientContact)),
        aiAssisted: value.aiAssisted,
        isAnonymous: value.isAnonymous,
        openingLine: value.openingLine,
        letterType: value.letterType,
        deliveryMethod: value.deliveryMethod,
        onThisDaySurfaced: value.onThisDaySurfaced,
        deliveryTime: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deliveryTime)),
        recipientUserId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.recipientUserId)),
        crisisSignalDetected: value.crisisSignalDetected,
        closingLine: value.closingLine,
        bodyText: value.bodyText,
        visibility: value.visibility,
        recipientType: value.recipientType,
        sharedWarmthTriggered: value.sharedWarmthTriggered,
        senderUserId: value.senderUserId,
        nonVeilTokenExpires: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.nonVeilTokenExpires)),
        openedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.openedAt))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    deliveredAt: [] | [bigint];
    apologyId: string;
    rescheduleCount: bigint;
    cancelledAt: [] | [bigint];
    scheduledDeliveryTime: bigint;
    reminderSent: boolean;
    reminderSentAt: [] | [bigint];
    senderUserId: Principal;
}): {
    id: string;
    status: string;
    deliveredAt?: bigint;
    apologyId: string;
    rescheduleCount: bigint;
    cancelledAt?: bigint;
    scheduledDeliveryTime: bigint;
    reminderSent: boolean;
    reminderSentAt?: bigint;
    senderUserId: Principal;
} {
    return {
        id: value.id,
        status: value.status,
        deliveredAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deliveredAt)),
        apologyId: value.apologyId,
        rescheduleCount: value.rescheduleCount,
        cancelledAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.cancelledAt)),
        scheduledDeliveryTime: value.scheduledDeliveryTime,
        reminderSent: value.reminderSent,
        reminderSentAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.reminderSentAt)),
        senderUserId: value.senderUserId
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: Principal;
    platform: string;
    activationCount: bigint;
    setupDate: [] | [bigint];
    setupCompleted: boolean;
    lastActivatedAt: [] | [bigint];
    phrase: string;
}): {
    userId: Principal;
    platform: string;
    activationCount: bigint;
    setupDate?: bigint;
    setupCompleted: boolean;
    lastActivatedAt?: bigint;
    phrase: string;
} {
    return {
        userId: value.userId,
        platform: value.platform,
        activationCount: value.activationCount,
        setupDate: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.setupDate)),
        setupCompleted: value.setupCompleted,
        lastActivatedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.lastActivatedAt)),
        phrase: value.phrase
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    completedAt: [] | [bigint];
    emotionSelected: string;
    receiverUserId: Principal;
    journalEntryId: [] | [string];
    createdAt: bigint;
    privateReflectionText: [] | [string];
    apologyId: string;
    actionTaken: string;
    reflectionComplete: boolean;
}): {
    id: string;
    completedAt?: bigint;
    emotionSelected: string;
    receiverUserId: Principal;
    journalEntryId?: string;
    createdAt: bigint;
    privateReflectionText?: string;
    apologyId: string;
    actionTaken: string;
    reflectionComplete: boolean;
} {
    return {
        id: value.id,
        completedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.completedAt)),
        emotionSelected: value.emotionSelected,
        receiverUserId: value.receiverUserId,
        journalEntryId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.journalEntryId)),
        createdAt: value.createdAt,
        privateReflectionText: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.privateReflectionText)),
        apologyId: value.apologyId,
        actionTaken: value.actionTaken,
        reflectionComplete: value.reflectionComplete
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    surfaceTypeUsed: [] | [string];
    significanceScore: number;
    eligibleForReturnAfter: _Time;
    userId: Principal;
    usedInSurface: boolean;
    rawEmotionIntensity: bigint;
    createdAt: _Time;
    contextSnapshot: string;
    signalIntensity: number;
    rawEmotionType: string;
    returnedAt: [] | [_Time];
    signalType: string;
}): {
    id: string;
    surfaceTypeUsed?: string;
    significanceScore: number;
    eligibleForReturnAfter: Time;
    userId: Principal;
    usedInSurface: boolean;
    rawEmotionIntensity: bigint;
    createdAt: Time;
    contextSnapshot: string;
    signalIntensity: number;
    rawEmotionType: string;
    returnedAt?: Time;
    signalType: string;
} {
    return {
        id: value.id,
        surfaceTypeUsed: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.surfaceTypeUsed)),
        significanceScore: value.significanceScore,
        eligibleForReturnAfter: value.eligibleForReturnAfter,
        userId: value.userId,
        usedInSurface: value.usedInSurface,
        rawEmotionIntensity: value.rawEmotionIntensity,
        createdAt: value.createdAt,
        contextSnapshot: value.contextSnapshot,
        signalIntensity: value.signalIntensity,
        rawEmotionType: value.rawEmotionType,
        returnedAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.returnedAt)),
        signalType: value.signalType
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    deliveredAt: [] | [_Time];
    surfaceType: string;
    userId: Principal;
    createdAt: _Time;
    deliveryStatus: string;
    scheduledForSessionAfter: _Time;
    signalId: string;
    dismissed: boolean;
}): {
    id: string;
    deliveredAt?: Time;
    surfaceType: string;
    userId: Principal;
    createdAt: Time;
    deliveryStatus: string;
    scheduledForSessionAfter: Time;
    signalId: string;
    dismissed: boolean;
} {
    return {
        id: value.id,
        deliveredAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.deliveredAt)),
        surfaceType: value.surfaceType,
        userId: value.userId,
        createdAt: value.createdAt,
        deliveryStatus: value.deliveryStatus,
        scheduledForSessionAfter: value.scheduledForSessionAfter,
        signalId: value.signalId,
        dismissed: value.dismissed
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    editLevel: string;
    nonVeilToken: [] | [string];
    signature: string;
    emotionType: string;
    sharedSilenceTriggered: boolean;
    content: string;
    deliveredAt: [] | [bigint];
    acknowledgedAt: [] | [bigint];
    aiVersionUsed: string;
    source: string;
    createdAt: bigint;
    recipientContact: [] | [string];
    aiAssisted: boolean;
    isAnonymous: boolean;
    deliveryMethod: string;
    deliveryTime: [] | [bigint];
    recipientUserId: [] | [Principal];
    rescheduleCount: bigint;
    crisisSignalDetected: boolean;
    visibility: string;
    recipientType: string;
    senderUserId: Principal;
    nonVeilTokenExpires: [] | [bigint];
    openedAt: [] | [bigint];
}): {
    id: string;
    status: string;
    editLevel: string;
    nonVeilToken?: string;
    signature: string;
    emotionType: string;
    sharedSilenceTriggered: boolean;
    content: string;
    deliveredAt?: bigint;
    acknowledgedAt?: bigint;
    aiVersionUsed: string;
    source: string;
    createdAt: bigint;
    recipientContact?: string;
    aiAssisted: boolean;
    isAnonymous: boolean;
    deliveryMethod: string;
    deliveryTime?: bigint;
    recipientUserId?: Principal;
    rescheduleCount: bigint;
    crisisSignalDetected: boolean;
    visibility: string;
    recipientType: string;
    senderUserId: Principal;
    nonVeilTokenExpires?: bigint;
    openedAt?: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        editLevel: value.editLevel,
        nonVeilToken: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.nonVeilToken)),
        signature: value.signature,
        emotionType: value.emotionType,
        sharedSilenceTriggered: value.sharedSilenceTriggered,
        content: value.content,
        deliveredAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deliveredAt)),
        acknowledgedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.acknowledgedAt)),
        aiVersionUsed: value.aiVersionUsed,
        source: value.source,
        createdAt: value.createdAt,
        recipientContact: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.recipientContact)),
        aiAssisted: value.aiAssisted,
        isAnonymous: value.isAnonymous,
        deliveryMethod: value.deliveryMethod,
        deliveryTime: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.deliveryTime)),
        recipientUserId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.recipientUserId)),
        rescheduleCount: value.rescheduleCount,
        crisisSignalDetected: value.crisisSignalDetected,
        visibility: value.visibility,
        recipientType: value.recipientType,
        senderUserId: value.senderUserId,
        nonVeilTokenExpires: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.nonVeilTokenExpires)),
        openedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.openedAt))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompanionDump>): Array<CompanionDump> {
    return value.map((x)=>from_candid_CompanionDump_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Confession>): Array<Confession> {
    return value.map((x)=>from_candid_Confession_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmotionEntry>): Array<EmotionEntry> {
    return value.map((x)=>from_candid_EmotionEntry_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FutureLetterDelivery>): Array<FutureLetterDelivery> {
    return value.map((x)=>from_candid_FutureLetterDelivery_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LoveLetter>): Array<LoveLetter> {
    return value.map((x)=>from_candid_LoveLetter_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApologyEntry>): Array<ApologyEntry> {
    return value.map((x)=>from_candid_ApologyEntry_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApologySchedule>): Array<ApologySchedule> {
    return value.map((x)=>from_candid_ApologySchedule_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SignificanceSignal>): Array<SignificanceSignal> {
    return value.map((x)=>from_candid_SignificanceSignal_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SurfaceDelivery>): Array<SurfaceDelivery> {
    return value.map((x)=>from_candid_SurfaceDelivery_n50(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
